# Generated by Django 5.0.2 on 2024-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.TextField(),
        ),
    ]
