# Generated by Django 5.0.2 on 2024-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_answers_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='watched_count',
            field=models.IntegerField(default=0),
        ),
    ]
