# Generated by Django 5.0.2 on 2024-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_rename_answers_answer_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='watched_count',
            field=models.FloatField(default=0),
        ),
    ]
