# Generated by Django 5.0.2 on 2024-03-30 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_alter_test_id_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='uuid',
            new_name='user',
        ),
    ]
