# Generated by Django 5.0.2 on 2024-04-08 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_rename_created_by_test_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
    ]
