# Generated by Django 5.0.2 on 2024-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_name_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='watched_count',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
