# Generated by Django 5.0.2 on 2024-04-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_test_likes_alter_test_watched_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='title',
            new_name='name',
        ),
    ]
